# 生产环境
server:
  port: 83
spring:
  datasource:
    url: jdbc:mysql://180.76.58.205:3306/private_diary
    username: root
    password: 970712
    tomcat:
      max-idle: 0
      max-active: 50
      max-wait: 1000
      initial-size: 10
      default-transaction-isolation: 2
  servlet:
    multipart:
      location: F:Files/
  redis:
    host: 180.76.58.205
    password: 123456
    timeout: 1000
  mail:
    host: smtp.163.com
    username: qq2544697696@163.com
    password: DBTQLRXWXWROYWMF
    protocol: smtp
    default-encoding: UTF-8
