# 测试环境配置
server:
  port: 88
spring:
  devtools:
    restart:
      enabled: true
  freemarker:
    cache: false
  datasource:
    url: jdbc:mysql://8.136.133.5:3306/private_diary
    username: root
    password: Guzx.@970712
  servlet:
    multipart:
      location: /home/files/
  redis:
    host: 8.136.133.5
    port: 6379
    password: Guzx.@970712
    timeout: 10000
  mail:
    host: smtp.163.com
    username: qq2544697696@163.com
    password: DBTQLRXWXWROYWMF
    protocol: smtp
    default-encoding: UTF-8
image:
  baseImagePath: /home/files/
